aws_region = "us-east-1"
service_name = "elasticache"
engine_name  = "redis"
node_type  = "cache.m4.large"
cache_count  = 1
parameter_group_name  = "default.redis6.x"
engine_version = "6.0"
port = 6379
team             = "CloudOps"
environment      = "Practice"
owner            = "Ramya Sri Rayapusetty"
owner_email = "ramyasrirayapusetty@gmail.com"
